var CANVAS_WIDTH=1024,CANVAS_HEIGHT=768,EDGEBOARD_X=0,EDGEBOARD_Y=120,FPS=30,WEB_FONT="Arial-Bold",PRIMARY_FONT="RobotoCondensed-Bold",SECONDARY_FONT="Digital-7",TERTIARY_FONT="RobotoCondensed-BoldItalic",STATE_LOADING=0,STATE_MENU=1,STATE_BET_PANEL=2,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,BET_PANEL_X=43,BET_PANEL_Y=165,BET_PANEL_WIDTH,BET_PANEL_HEIGHT,GREYHOUND_WIDTH=338,GREYHOUND_HEIGHT=170,CHIP_VALUES,NUM_CHIPS,NUM_GREYHOUNDS,MIN_BET,
MAX_BET,WIN_OCCURRENCE,NUM_TRACK_BG=18,ARRIVAL_X=491,TIME_CHECK_RANK=3E3,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS,DISABLE_SOUND_MOBILE=!1,SOURCE_PATH="",START_CREDIT=0,MY_BALANCES=[{name:"TRX",available:100},{name:"DOGE",available:9884},{name:"LTC",available:1.345}],MY_ODDS={COIN_TYPE:0,ODDS:[0,0,0]},GAME_ODDS_RATE=[1,2,2E-4];
number_format=function(b,d,c,a){b=isFinite(+b)?+b:0;d=isFinite(+d)?Math.abs(d):0;a="undefined"===typeof a?",":a;c="undefined"===typeof c?".":c;var f="";f=function(a,b){var e=Math.pow(10,b);return""+Math.round(a*e)/e};f=(d?f(b,d):""+Math.round(b)).split(".");3<f[0].length&&(f[0]=f[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,a));(f[1]||"").length<d&&(f[1]=f[1]||"",f[1]+=Array(d-f[1].length+1).join("0"));return f.join(c)};
numberFormat=function(b,d){d=d||{};"undefined"===typeof d.decpoint&&(d.decpoint=".");"undefined"===typeof d.sep&&(d.sep=",");"undefined"===typeof d.decimals&&(d.decimals=0);b=Number(b);if(1>b&&0<b){var c=b.toFixed(d.decimals).split("."),a=c[1].length;d.limit_length_decimals&&d.limit_length_decimals<a&&(a=d.limit_length_decimals);if(d.clear_decimals)for(var f=a-1;0<=f&&!(0<c[1][f]);f--)a--;return b.toFixed(a)}if(d.decimals&&d.clear_decimals)if(c=b.toString().split("."),1==c.length)d.decimals=0;else{var k=
c[1].substring(0,d.decimals);a=k.length;for(f=k.length-1;0<=f&&!(0<k[f]);f--)a--;d.decimals=a;d.limit_length_decimals&&(c=d.limit_length_decimals-c[0].length,0>c&&(c=0),d.decimals>c&&(d.decimals=c))}return number_format(b,d.decimals,d.decpoint,d.sep)};function copyToClipboard(b,d){d||(d="Copied");$("#"+b).focus();$("#"+b).select();document.execCommand("copy");var c='<p id="da-sao-chep"> '+d+" </p>";$("body").append(c);setTimeout(function(){$("#da-sao-chep").remove()},2E3)}
function copyToClipboard2(b,d,c){c||(c="Copied");if(document.selection){document.selection.empty();var a=document.body.createTextRange();a.moveToElementText(document.getElementById(b));a.select().createTextRange();document.execCommand("copy");2==d?(d=$("#"+b).offset().top,40<d?d-=40:d=0,b=$("#"+b).offset().left,c='<p id="alert-copyed" style="top:'+d+"px; left: "+b+'px"> '+c+" </p>",$("body").append(c),setTimeout(function(){$("#alert-copyed").remove()},800)):1==d&&alert(c+": "+window.getSelection())}else window.getSelection&&
(window.getSelection().removeAllRanges(),a=document.createRange(),a.selectNode(document.getElementById(b)),window.getSelection().addRange(a),document.execCommand("copy"),2==d?(d=$("#"+b).offset().top,40<d?d-=40:d=0,b=$("#"+b).offset().left,c='<p id="alert-copyed" style="top:'+d+"px; left: "+b+'px"> '+c+" </p>",$("body").append(c),setTimeout(function(){$("#alert-copyed").remove()},800)):1==d&&alert(c+": "+window.getSelection()))}function validateContainsLetter(b){return/[a-zA-Z]/.test(String(b))}
function validateMinMax(b,d,c){return!b||d&&b.length<d||c&&b.length>c?!1:!0}function validateNickname(b){return/^[0-9A-Za-z\-]+$/.test(String(b))}function validateEmail(b){return/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(String(b).toLowerCase())}function validateOnlyNumber(b){return/^\d+$/.test(String(b))}
(function(){var b={};window.gConfig=b;b.namespace="GreyhoundRacing";b.userInfo={forSound:!0,MY_ODDS:{COIN_TYPE:0,ODDS:[0,0,0]}};b.onDeviceReady=function(){var d=window.localStorage.getItem(b.namespace+"/userInfo");null==d?window.localStorage.setItem(b.namespace+"/userInfo",JSON.stringify(b.userInfo)):b.userInfo=JSON.parse(d);s_bAudioActive=b.userInfo.forSound;MY_ODDS=b.userInfo.MY_ODDS;window.userBalances&&userBalances.DOGE&&(MY_BALANCES[1].available=Number(userBalances.DOGE));window.userBalances&&
userBalances.LTC&&(MY_BALANCES[2].available=Number(userBalances.LTC))};b.updateUserInfo=function(){window.localStorage.setItem(b.namespace+"/userInfo",JSON.stringify(b.userInfo))}})();
var TEXT_CURRENCY="$",TEXT_START_RACE="START RACE",TEXT_CLEAR_BET="CLEAR BET",TEXT_MONEY="MONEY",TEXT_BET="TOTAL BET",TEXT_MIN_BET="MIN BET",TEXT_MAX_BET="MAX BET",TEXT_TRAP="TRAP",TEXT_GREYHOUND_NAME="GREYHOUND NAME",TEXT_ODDS="ODDS",TEXT_WINS="WINS",TEXT_PLACE="PLACE",TEXT_SHOW="SHOW",TEXT_WIN="WIN",TEXT_NO_WIN="NO WIN",TEXT_NO_MONEY="NOT ENOUGH MONEY!!",TEXT_ERR_MAX_BET="YOUR BET IS HIGHER THAN MAXIMUM ONE!!",TEXT_ERR_MIN_BET="YOUR BET IS LOWER THAN MINIMUM ONE!!",TEXT_ARE_YOU_SURE="IF YOU EXIT THE RESULT\tWILL NOT CHANGE!",
TEXT_BUT_HELP="HELP",TEXT_HELP_PAGE_0="",TEXT_HELP_PAGE_1="",TEXT_IS_PREPARING="PREPARING !!",s_iScaleFactor=1,s_iOffsetX=0,s_iOffsetY=0,s_bIsIphone=!1,s_bIsRetina=!1,s_oOrientationOk=!0;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);function trace(b){console.log(b)}$(window).resize(function(){sizeHandler()});function isRetina(){s_bIsRetina=window.matchMedia("(-webkit-min-device-pixel-ratio: 2), (min-device-pixel-ratio: 2), (min-resolution: 192dpi)").matches?!0:!1}function isIOS(){isRetina();for(var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");b.length;)if(navigator.platform===b.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(b){var d=b.toLowerCase(),c=window.document,a=c.documentElement;if(void 0===window["inner"+b])b=a["client"+b];else if(window["inner"+b]!=a["client"+b]){var f=c.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var k=c.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+d+":"+a["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";f.appendChild(k);a.insertBefore(f,c.head);
b=7==k["offset"+b]?a["client"+b]:window["inner"+b];a.removeChild(f)}else b=window["inner"+b];return b}function getIOSWindowHeight(){return window.innerHeight*document.documentElement.clientWidth/window.innerWidth}function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler1(){window.scrollTo(0,1);if($("#canvas")){var b=CANVAS_WIDTH,d=CANVAS_HEIGHT,c=window.innerWidth;multiplier=Math.min(window.innerHeight/d,c/b);b*=multiplier;d*=multiplier;$("#canvas").css("width",b+"px");$("#canvas").css("height",d+"px");$("#canvas").css("left",c/2-b/2+"px")}}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height"),d=getSize("Width");_checkOrientation(d,b);var c=Math.min(b/CANVAS_HEIGHT,d/CANVAS_WIDTH),a=CANVAS_WIDTH*c;c*=CANVAS_HEIGHT;if(c<b){var f=b-c;c+=f;a+=CANVAS_WIDTH/CANVAS_HEIGHT*f}else a<d&&(f=d-a,a+=f,c+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=b/2-c/2;var k=d/2-a/2,e=CANVAS_WIDTH/a;if(k*e<-EDGEBOARD_X||f*e<-EDGEBOARD_Y)c=Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
d/(CANVAS_WIDTH-2*EDGEBOARD_X)),a=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,f=(b-c)/2,k=(d-a)/2,e=CANVAS_WIDTH/a;s_iOffsetX=-1*k*e;s_iOffsetY=-1*f*e;0<=f&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);window.s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);window.s_oGame&&s_oGame.refreshButtonPos(s_iOffsetX,s_iOffsetY);window.s_oBetPanel&&s_oBetPanel.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsRetina?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*a,s_oStage.canvas.height=2*c,canvas.style.width=
a+"px",canvas.style.height=c+"px",b=Math.min(a/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_iScaleFactor=2*b,s_oStage.scaleX=s_oStage.scaleY=2*b):s_bMobile?($("#canvas").css("width",a+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=a,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(a/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);$("#canvas").css("top",f+"px");$("#canvas").css("left",k+"px");fullscreenHandler()}}
function _checkOrientation(b,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(b>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oOrientationOk=!0,s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oOrientationOk=!1,s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oOrientationOk=!0,s_oMain.startUpdate()):
($(".orientation-msg-container").css("display","block"),s_oOrientationOk=!1,s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(b){return!0}}function createBitmap(b,d,c){b=new createjs.Bitmap(b);if(d&&c){var a=new createjs.Shape;a.graphics.beginFill("#fff").drawRect(0,0,d,c);b.hitArea=a}return b}
function createSprite(b,d,c,a,f,k){b=null!==d?new createjs.Sprite(b,d):new createjs.Sprite(b);void 0!==c&&void 0!==a&&void 0!==f&&void 0!==k&&(d=new createjs.Shape,d.graphics.beginFill("#000000").drawRect(c,a,f,k),b.hitArea=d);return b}function shuffle(b){for(var d=b.length,c,a;0<d;)a=Math.floor(Math.random()*d),d--,c=b[d],b[d]=b[a],b[a]=c;return b}
Array.prototype.sortOn=function(){var b=this.slice();if(!arguments.length)return b.sort();var d=Array.prototype.slice.call(arguments);return b.sort(function(b,a){for(var f=d.slice(),c=f.shift();b[c]==a[c]&&f.length;)c=f.shift();return b[c]==a[c]?0:b[c]>a[c]?1:-1})};function getParamValue(b){for(var d=window.location.search.substring(1).split("&"),c=0;c<d.length;c++){var a=d[c].split("=");if(a[0]==b)return a[1]}}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}
function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function playSound(b,d,c){return s_aSounds&&s_aSounds[b]?(s_aSounds[b].play(),s_aSounds[b].volume(d),s_aSounds[b].loop(c),s_aSounds[b]):null}function soundIsPlaying(b){return s_aSounds&&s_aSounds[b]&&s_aSounds[b].playing()||!1}function pauseSound(b){s_aSounds&&s_aSounds[b]&&s_aSounds[b].pause()}function stopSound(b){s_aSounds&&s_aSounds[b]&&s_aSounds[b].stop()}function setVolume(b,d){s_aSounds&&s_aSounds[b]&&s_aSounds[b].volume(d)}
function setMute(b,d){s_aSounds&&s_aSounds[b]&&s_aSounds[b].mute(d)}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
(function(){function b(b){var a={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in a?document.body.className=a[b.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oOrientationOk&&s_oMain.stopUpdate():s_oOrientationOk&&s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",b):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",
b):(d="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",b):(d="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();
(function(){var b="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},d="undefined"!==typeof module&&module.exports,c="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,a=function(){for(var a,f=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],c=0,d=f.length,m={};c<d;c++)if((a=f[c])&&a[1]in b){for(c=0;c<a.length;c++)m[f[0][c]]=
a[c];return m}return!1}(),f={change:a.fullscreenchange,error:a.fullscreenerror},k={request:function(e){var f=a.requestFullscreen;e=e||b.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))e[f]();else e[f](c&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){b[a.exitFullscreen]()},toggle:function(a){this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},on:function(a,c){var e=f[a];e&&b.addEventListener(e,c,!1)},off:function(a,
c){var e=f[a];e&&b.removeEventListener(e,c,!1)},raw:a};a?(Object.defineProperties(k,{isFullscreen:{get:function(){return!!b[a.fullscreenElement]}},element:{enumerable:!0,get:function(){return b[a.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!b[a.fullscreenEnabled]}}}),d?module.exports=k:window.screenfull=k):d?module.exports=!1:window.screenfull=!1})();
function fullscreenHandler(){ENABLE_FULLSCREEN&&!inIframe()&&s_bFullscreen!=(screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1)&&(window.s_oInterface&&s_oInterface.resetFullscreenBut(2),window.s_oMenu&&s_oMenu.resetFullscreenBut(2),window.s_oBetPanel&&s_oBetPanel.resetFullscreenBut(2))}
if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;window.s_oInterface&&s_oInterface.resetFullscreenBut(1);window.s_oMenu&&s_oMenu.resetFullscreenBut(1);window.s_oBetPanel&&s_oBetPanel.resetFullscreenBut(1)});
function CSpriteLibrary(){var b,d,c,a,f,k;this.init=function(e,h,l){c=d=0;a=e;f=h;k=l;b={}};this.addSprite=function(a,c){b.hasOwnProperty(a)||(b[a]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(a){return b.hasOwnProperty(a)?b[a].oSprite:null};this._onSpritesLoaded=function(){f.call(k)};this._onSpriteLoaded=function(){a.call(k);++c===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,b[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
b[a].oSprite.src=b[a].szPath};this.getNumSprites=function(){return d}}
function CGameSettings(b){var d,c,a,f,k,e,h,l,g;this._init=function(a){g=a;d=g.greyhound_names;NUM_GREYHOUNDS=d.length;this._initSimpleOdd();this._initForecastOdd();this._initPaths();this._initGreyhoundInfo();e=CHIP_VALUES};this._initSimpleOdd=function(){c=g.odd_win_bet;a=g.odd_place_bet;f=g.odd_show_bet};this._initForecastOdd=function(){var a=g.forecast;k=[];for(var b=0;b<NUM_GREYHOUNDS;b++)k[b]=[];for(b=0;b<a.length;b++)k[a[b].first-1][a[b].second-1]=a[b].odd};this._initPaths=function(){h=[];var a=
[{x:230,frame:30},{x:500,frame:180},{x:600,frame:180},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],b=[{x:250,frame:30},{x:600,frame:200},{x:650,frame:180},{x:450,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],e=[{x:170,frame:30},{x:400,frame:150},{x:450,frame:210},{x:400,frame:140},{x:300,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],
c=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],f=[{x:220,frame:30},{x:350,frame:280},{x:480,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-450,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],d=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-600,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,place_6:d});
a=[{x:230,frame:30},{x:450,frame:180},{x:500,frame:180},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:250,frame:30},{x:600,frame:200},{x:550,frame:180},{x:350,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:170,frame:30},{x:450,frame:150},{x:550,frame:210},{x:500,frame:140},{x:400,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
c=[{x:190,frame:30},{x:300,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-450,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:210,frame:30},{x:360,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-600,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,place_6:d});
a=[{x:230,frame:30},{x:500,frame:180},{x:600,frame:180},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:250,frame:30},{x:600,frame:200},{x:650,frame:180},{x:500,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:170,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:450,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
c=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:220,frame:30},{x:350,frame:280},{x:480,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,place_6:d});
a=[{x:330,frame:30},{x:450,frame:180},{x:550,frame:180},{x:650,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:250,frame:30},{x:350,frame:200},{x:450,frame:180},{x:600,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
c=[{x:290,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:210,frame:30},{x:360,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,place_6:d});
a=[{x:230,frame:30},{x:350,frame:180},{x:400,frame:180},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:250,frame:30},{x:350,frame:200},{x:450,frame:180},{x:500,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
c=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,place_6:d});
a=[{x:230,frame:50},{x:350,frame:200},{x:400,frame:100},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:250},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:250,frame:100},{x:350,frame:150},{x:450,frame:150},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:270,frame:50},{x:400,frame:150},{x:450,frame:200},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:190,frame:30},
{x:340,frame:170},{x:360,frame:300},{x:380,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:220,frame:100},{x:350,frame:200},{x:400,frame:200},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:210,frame:50},{x:260,frame:300},{x:300,frame:200},{x:220,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:150},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,
place_4:c,place_5:f,place_6:d});a=[{x:230,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:250,frame:100},{x:350,frame:150},{x:450,frame:150},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:270,frame:50},{x:200,frame:150},{x:450,frame:400},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:190,frame:30},{x:340,frame:170},
{x:360,frame:300},{x:380,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:220,frame:100},{x:350,frame:200},{x:400,frame:200},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:210,frame:50},{x:260,frame:300},{x:300,frame:200},{x:220,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:150},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,
place_6:d});a=[{x:230,frame:50},{x:250,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:250,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:270,frame:50},{x:330,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:190,frame:50},{x:230,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:30}];f=[{x:220,frame:50},{x:300,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:210,frame:50},{x:130,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,place_6:d});a=[{x:210,frame:50},{x:130,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:220,frame:50},{x:300,frame:300},{x:ARRIVAL_X-
GREYHOUND_WIDTH/2-150,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:270,frame:50},{x:330,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:190,frame:50},{x:190,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:230,frame:50},{x:250,frame:300},{x:ARRIVAL_X-
GREYHOUND_WIDTH/2-650,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,place_6:d});a=[{x:330,frame:30},{x:450,frame:180},{x:550,frame:180},{x:650,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];b=[{x:250,frame:90},{x:450,frame:300},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},
{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:290,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:310,frame:30},{x:400,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-
650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:a,place_2:b,place_3:e,place_4:c,place_5:f,place_6:d})};this._initGreyhoundInfo=function(){l=[];l[0]={start:new createjs.Point(208,342),scale:.66};l[1]={start:new createjs.Point(186,352),scale:.7};l[2]={start:new createjs.Point(163,363),scale:.74};l[3]={start:new createjs.Point(134,376),scale:.8};l[4]={start:new createjs.Point(99,394),scale:.9};l[5]={start:new createjs.Point(53,415),scale:1}};this.getIndexForFiches=function(a){for(var b=
0,c=0;c<e.length;c++)e[c]===a&&(b=c);return b};this.getGreyhoundPercentageArray=function(){for(var a=[],b=0;b<c.length;b++)for(var e=Math.floor(c[b]),f=0;f<e;f++)a.push(b);return a=shuffle(a)};this.getGreyhoundName=function(a){return d[a]};this.getAllGreyhoundNames=function(){return d};this.getOddWin=function(a){return c[a]};this.getOddPlace=function(b){return a[b]};this.getOddShow=function(a){return f[a]};this.getForecastOdd=function(a,b){return k[a][b]};this.getRandomPath=function(){return h[Math.floor(Math.random()*
h.length)]};this.getGreyhoundInfo=function(a){return l[a]};s_oGameSettings=this;this._init(b)}var s_oGameSettings=null;
function CPreloader(){var b,d,c,a,f,k,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){e.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(k).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));e.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");a=createBitmap(h);a.x=CANVAS_WIDTH/2-h.width/2;a.y=CANVAS_HEIGHT-240;e.addChild(a);b=h.width;d=h.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(a.x,a.y,1,d);e.addChild(f);
a.mask=f;c=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-250;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";e.addChild(c);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;e.addChild(k)};this.refreshLoader=function(e){c.text=e+"%";f.graphics.clear();e=Math.floor(e*b/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(a.x,a.y,e,d)};this._init()}
function CMain(b){var d=0,c=0,a,f=STATE_LOADING,k,e;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(10),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader};this.preloaderReady=function(){this.onLoadedJSON({greyhound_names:"psycho;all saturdays;the norman;t-rex;nice tuft;baloo".split(";"),odd_win_bet:[1.5,1.8,2,2.2,2.5,3],odd_place_bet:[1.95,2.55,1.25,5.5,7.75,3.05],odd_show_bet:[1.25,1.7,1.09,2.55,3.9,1.75],forecast:[{first:1,second:2,odd:20},{first:1,second:3,odd:8},{first:1,second:4,odd:30},{first:1,second:5,odd:40},{first:1,second:6,odd:23},{first:2,second:1,odd:24},{first:2,
second:3,odd:10},{first:2,second:4,odd:25},{first:2,second:5,odd:28},{first:2,second:6,odd:38},{first:3,second:1,odd:6},{first:3,second:2,odd:9},{first:3,second:4,odd:26},{first:3,second:5,odd:31},{first:3,second:6,odd:9},{first:4,second:1,odd:84},{first:4,second:2,odd:56},{first:4,second:3,odd:23},{first:4,second:5,odd:80},{first:4,second:6,odd:65},{first:5,second:1,odd:70},{first:5,second:2,odd:70},{first:5,second:3,odd:68},{first:5,second:4,odd:84},{first:5,second:6,odd:80},{first:6,second:1,odd:38},
{first:6,second:2,odd:48},{first:6,second:3,odd:13},{first:6,second:4,odd:50},{first:6,second:5,odd:60}]});a=!0};this.onLoadedJSON=function(a){s_oGameSettings=new CGameSettings(a);s_oBetList=new CBetList;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_oMain._initSounds();s_oMain._loadImages()};this.soundLoaded=function(){c++;k.refreshLoader(Math.floor(c/d*100));c===d&&s_oMain._onRemovePreloader()};this._initSounds=function(){var a=[];a.push({path:SOURCE_PATH+"sounds/",filename:"chip",loop:!1,volume:1,
ingamename:"chip"});a.push({path:SOURCE_PATH+"sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});a.push({path:SOURCE_PATH+"sounds/",filename:"start_race",loop:!1,volume:1,ingamename:"start_race"});a.push({path:SOURCE_PATH+"sounds/",filename:"photo",loop:!1,volume:1,ingamename:"photo"});a.push({path:SOURCE_PATH+"sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});d+=a.length;s_aSounds=[];for(var b=0;b<a.length;b++)s_aSounds[a[b].ingamename]=new Howl({src:[a[b].path+
a[b].filename+".mp3",a[b].path+a[b].filename+".ogg"],autoplay:!1,preload:!0,loop:a[b].loop,volume:a[b].volume,onload:s_oMain.soundLoaded})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_exit",SOURCE_PATH+"sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon",SOURCE_PATH+"sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_play",SOURCE_PATH+"sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart",
SOURCE_PATH+"sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home",SOURCE_PATH+"sprites/but_credits.png");s_oSpriteLibrary.addSprite("msg_box",SOURCE_PATH+"sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_fullscreen",SOURCE_PATH+"sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_no",SOURCE_PATH+"sprites/but_no.png");s_oSpriteLibrary.addSprite("but_yes",SOURCE_PATH+"sprites/but_yes.png");s_oSpriteLibrary.addSprite("arrow_left",SOURCE_PATH+"sprites/arrow_left.png");s_oSpriteLibrary.addSprite("arrow_right",
SOURCE_PATH+"sprites/arrow_right.png");s_oSpriteLibrary.addSprite("fiche_0",SOURCE_PATH+"sprites/fiche_0.png");s_oSpriteLibrary.addSprite("fiche_1",SOURCE_PATH+"sprites/fiche_1.png");s_oSpriteLibrary.addSprite("fiche_2",SOURCE_PATH+"sprites/fiche_2.png");s_oSpriteLibrary.addSprite("fiche_3",SOURCE_PATH+"sprites/fiche_3.png");s_oSpriteLibrary.addSprite("fiche_4",SOURCE_PATH+"sprites/fiche_4.png");s_oSpriteLibrary.addSprite("fiche_5",SOURCE_PATH+"sprites/fiche_5.png");s_oSpriteLibrary.addSprite("bg_bet_panel",
SOURCE_PATH+"sprites/bg_bet_panel.jpg");s_oSpriteLibrary.addSprite("money_panel",SOURCE_PATH+"sprites/money_panel.png");s_oSpriteLibrary.addSprite("simple_bet_panel",SOURCE_PATH+"sprites/simple_bet_panel.png");s_oSpriteLibrary.addSprite("forecast_panel",SOURCE_PATH+"sprites/forecast_panel.png");s_oSpriteLibrary.addSprite("bet_place",SOURCE_PATH+"sprites/bet_place.png");s_oSpriteLibrary.addSprite("fiche_highlight",SOURCE_PATH+"sprites/fiche_highlight.png");s_oSpriteLibrary.addSprite("odd_bg",SOURCE_PATH+
"sprites/odd_bg.png");s_oSpriteLibrary.addSprite("rank_panel",SOURCE_PATH+"sprites/rank_panel.png");s_oSpriteLibrary.addSprite("panel_arrival",SOURCE_PATH+"sprites/panel_arrival.png");s_oSpriteLibrary.addSprite("bibs",SOURCE_PATH+"sprites/bibs.png");s_oSpriteLibrary.addSprite("but_skip",SOURCE_PATH+"sprites/but_skip.png");s_oSpriteLibrary.addSprite("but_start_race",SOURCE_PATH+"sprites/but_start_race.png");s_oSpriteLibrary.addSprite("but_clear_bet",SOURCE_PATH+"sprites/but_clear_bet.png");s_oSpriteLibrary.addSprite("fiche_panel",
SOURCE_PATH+"sprites/fiche_panel.png");s_oSpriteLibrary.addSprite("fill_bar",SOURCE_PATH+"sprites/fill_bar.png");s_oSpriteLibrary.addSprite("win_panel",SOURCE_PATH+"sprites/win_panel.png");s_oSpriteLibrary.addSprite("coin_select_but",SOURCE_PATH+"sprites/but_coin.png");s_oSpriteLibrary.addSprite("money_bg",SOURCE_PATH+"sprites/money_bg.png");for(var a=0;a<NUM_GREYHOUNDS;a++)s_oSpriteLibrary.addSprite("bib_gui_"+a,SOURCE_PATH+"sprites/bib_gui_"+a+".png"),s_oSpriteLibrary.addSprite("greyhound_"+(a+
1),SOURCE_PATH+"sprites/greyhound_"+(a+1)+".png");for(a=0;a<NUM_TRACK_BG;a++)s_oSpriteLibrary.addSprite("bg_track_"+a,SOURCE_PATH+"sprites/bg_track/bg_track_"+a+".jpg");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;k.refreshLoader(Math.floor(c/d*100));c===d&&s_oMain._onRemovePreloader()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){k.unload();isIOS()||
(s_oSoundTrack=playSound("soundtrack",1,!0));this.gotoBetPanel()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoBetPanel=function(){new CBetPanel;f=STATE_BET_PANEL};this.gotoGame=function(a,b){e=new CGame(a,b);f=STATE_GAME};this.stopUpdate=function(){a=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!0===DISABLE_SOUND_MOBILE&&!0===s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();a=!0;createjs.Ticker.paused=!1;$("#block_game").css("display",
"none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(b){if(a){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&e.update();s_oStage.update(b)}};s_oMain=this;s_iCurMoney=START_CREDIT;CHIP_VALUES=b.chip_values;NUM_CHIPS=CHIP_VALUES.length;MIN_BET=b.min_bet;MAX_BET=b.max_bet;WIN_OCCURRENCE=b.win_occurrence;SHOW_CREDITS=
b.show_credits;ENABLE_FULLSCREEN=b.fullscreen;ENABLE_CHECK_ORIENTATION=b.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_bStorageAvailable=!0,s_iCurMoney,s_aSounds;
function CTextButton(b,d,c,a,f,k,e,h){var l,g,m,n,p,q,t;this._init=function(a,b,e,c,f,d,k){l=[];g=[];var h=createBitmap(e),q=Math.ceil(k/20);p=new createjs.Text(c,"bold "+k+"px "+f,"#000000");p.textAlign="center";p.textBaseline="alphabetic";var r=p.getBounds();p.x=e.width/2+q;p.y=Math.floor(e.height/2)+r.height/3+q;n=new createjs.Text(c,"bold "+k+"px "+f,d);n.textAlign="center";n.textBaseline="alphabetic";r=n.getBounds();n.x=e.width/2;n.y=Math.floor(e.height/2)+r.height/3;m=new createjs.Container;
m.x=a;m.y=b;m.regX=e.width/2;m.regY=e.height/2;m.addChild(h,p,n);u.addChild(m);s_bMobile||(m.cursor="pointer");this._initListener()};this.unload=function(){m.off("mousedown",q);m.off("pressup",t);u.removeChild(m)};this.setVisible=function(a){m.visible=a};this._initListener=function(){q=m.on("mousedown",this.buttonDown);t=m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){l[a]=b;g[a]=e};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("click",1,0);l[ON_MOUSE_UP]&&
l[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setTextPosition=function(a){n.y=a;p.y=a+2};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};var u=h;this._init(b,d,c,a,f,k,e);return this}
function CToggle(b,d,c,a,f){var k,e,h,l,g,m,n;this._init=function(a,b,c,f,d){n=void 0!==d?d:s_oStage;e=[];h=[];c=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});k=f;l=createSprite(c,"state_"+k);l.x=a;l.y=b;l.stop();s_bMobile||(l.cursor="pointer");n.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",g);l.off("pressup",m);n.removeChild(l)};this._initListener=function(){g=
l.on("mousedown",this.buttonDown);m=l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;h[a]=c};this.setCursorType=function(a){l.cursor=a};this.setActive=function(a){k=a;l.gotoAndStop("state_"+k)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("click",1,0);k=!k;l.gotoAndStop("state_"+k);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(h[ON_MOUSE_UP],k)};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=
function(a,b){l.x=a;l.y=b};this._init(b,d,c,a,f)}
function CGfxButton(b,d,c,a){var f,k,e,h,l,g,m,n,p,q=!1;this._init=function(a,b,c,d){p=void 0!==d?d:s_oStage;f=[];k=[];h=[];e=createBitmap(c);e.x=a;e.y=b;g=l=1;e.regX=c.width/2;e.regY=c.height/2;s_bMobile||(e.cursor="pointer");p.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",m);e.off("pressup",n);p.removeChild(e)};this.setVisible=function(a){e.visible=a};this.setCursorType=function(a){e.cursor=a};this._initListener=function(){m=e.on("mousedown",this.buttonDown);n=e.on("pressup",
this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;k[a]=c};this.addEventListenerWithParams=function(a,b,c,e){f[a]=b;k[a]=c;h[a]=e};this.buttonRelease=function(){q||(e.scaleX=0<l?l:-l,e.scaleY=g,playSound("click",1,0),f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(k[ON_MOUSE_UP],h[ON_MOUSE_UP]))};this.buttonDown=function(){q||(e.scaleX=0<l?.9*l:.9*-l,e.scaleY=.9*g,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],h[ON_MOUSE_DOWN]))};this.rotation=function(a){e.rotation=a};this.getButton=
function(){return e};this.setPosition=function(a,b){e.x=a;e.y=b};this.setX=function(a){e.x=a};this.setY=function(a){e.y=a};this.getButtonImage=function(){return e};this.block=function(a){q=a;e.scaleX=l;e.scaleY=g};this.setScaleX=function(a){l=e.scaleX=a};this.setScale=function(a){g=l=a;e.scaleX=e.scaleY=a};this.getX=function(){return e.x};this.getY=function(){return e.y};this.pulseAnimation=function(){createjs.Tween.get(e).to({scaleX:.9*l,scaleY:.9*g},850,createjs.Ease.quadOut).to({scaleX:l,scaleY:g},
650,createjs.Ease.quadIn).call(function(){t.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(e).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){t.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(e)};this._init(b,d,c,a);var t=this;return this}
function CSpriteButton(b,d,c,a,f){var k,e,h,l,g,m,n,p;this._init=function(a,b,c,f,d){m=void 0!==d?d:s_oStage;k=!1;h=[];l=[];c=new createjs.SpriteSheet({images:[c],frames:{width:c.width,height:c.height/3,regX:c.width/2,regY:c.height/6},animations:{frame0:[0],frame1:[1],frame2:[2]}});e="frame"+f;g=createSprite(c,e);g.x=a;g.y=b;g.stop();s_bMobile||(g.cursor="pointer");m.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",n);g.off("pressup",p);m.removeChild(g)};this._initListener=
function(){n=g.on("mousedown",this.buttonDown);p=g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;l[a]=c};this.setCursorType=function(a){g.cursor=a};this.gotoAndStop=function(a){e=a;g.gotoAndStop(a)};this.enable=function(){k=!1};this.disable=function(){k=!0};this.getCurrentFrame=function(){return g.currentFrame};this.buttonDown=function(){k||(g.scaleX=.9,g.scaleY=.9,h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN]))};this.buttonRelease=function(){k||(g.scaleX=
1,g.scaleY=1,playSound("click",1,!1),h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP],e))};this.setPosition=function(a,b){g.x=a;g.y=b};this._init(b,d,c,a,f)}
function CGame(b,d){var c,a,f,k,e,h,l,g,m,n,p,q,t,u,r,v,w;this._init=function(a){k=f=c=!1;l=h=0;p=s_oGameSettings.getAllGreyhoundNames();s_oTweenController=new CTweenController;q=new createjs.Container;s_oStage.addChild(q);u=new CTrackBg(q);v=new CRankingGui(p,s_oStage);w=new CArrivalPanel(CANVAS_WIDTH,240,s_oStage);r=new CInterface;t=new createjs.Shape;t.graphics.beginFill("white").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);t.alpha=0;s_oStage.addChild(t);this.refreshButtonPos(s_iOffsetX,s_iOffsetY);
s_oSoundTrack&&1==s_oSoundTrack.playing()&&s_oSoundTrack.stop();this._generateResultFromServer(a);this._prepareGreyHounds();setTimeout(function(){s_oGame.startRace()},100)};this.unload=function(){stopSound("start_race");createjs.Tween.removeAllTweens();r.unload();s_oStage.removeAllChildren();s_oGame=null};this.refreshButtonPos=function(a,b){r.refreshButtonPos(a,b);v.refreshButtonPos(a,b)};this.pause=function(){c=!1;pauseSound("start_race");for(var a=0;a<NUM_GREYHOUNDS;a++)n[a].pauseAnim()};this.unpause=
function(){c=!0;playSound("start_race");for(var a=0;a<NUM_GREYHOUNDS;a++)n[a].unpauseAnim()};this.onExit=function(){s_oSoundTrack&&0==s_oSoundTrack.playing()&&s_oSoundTrack.play();this.unload();s_oMain.gotoBetPanel()};this.gotoBetPanel=function(){s_oSoundTrack&&0==s_oSoundTrack.playing()&&s_oSoundTrack.play();this.unload();s_oMain.gotoBetPanel()};this.startRace=function(){playSound("start_race",1,0);r.blockExit(!1);c=!0};this._generateResultFromServer=function(a){g=a;a=s_oBetList.getTotWinWithCurRank(g);
e=a.tot_win;m=a.win_list};this.generateFinalRank=function(){100*Math.random()<WIN_OCCURRENCE?this._generateWinResult():this._generateLosingResult()};this._generateWinResult=function(){a=!0;do{g=this._generateRandomRank();var c=s_oBetList.getTotWinWithCurRank(g);e=c.tot_win}while(e<=b);m=c.win_list;for(var f in m)console.log(m[f].win)};this._generateLosingResult=function(){a=!1;do{g=this._generateRandomRank();var c=s_oBetList.getTotWinWithCurRank(g);e=c.tot_win}while(e>b);m=c.win_list;for(var f in m)console.log(m[f].win)};
this._generateRandomRank=function(){for(var a=[],b=s_oGameSettings.getGreyhoundPercentageArray();a.length<NUM_GREYHOUNDS;){var c=b[Math.floor(Math.random()*b.length)];a.unshift(c);for(var e=b.length-1;0<=e;)b[e]===c&&b.splice(e,1),e--}return a};this._prepareGreyHounds=function(){n=[];for(var a=s_oGameSettings.getRandomPath(),b=0;b<NUM_GREYHOUNDS;b++){var c=s_oGameSettings.getGreyhoundInfo(b),e=g.indexOf(b);n[b]=new CGreyhound(c.start,b+1,p[b],c.scale,a["place_"+(e+1)],q)}};this.startGreyhounds=function(){for(var a=
0;a<NUM_GREYHOUNDS;a++)n[a].startRace()};this.greyhoundPhotofinish=function(b,f){r.blockExit(!0);w.refreshRank(b,f);h++;if(4>h)c=!1,l=TIME_CHECK_RANK,this._playFlashAnim();else if(6===h){if(a||e)s_iCurMoney=START_CREDIT;r.showWinPanel(e,m,g);stopSound("start_race");s_oSoundTrack&&0==s_oSoundTrack.playing()&&s_oSoundTrack.play()}};this.checkGreyhoundArrival=function(){f=!0};this._playFlashAnim=function(){for(var a=0;a<NUM_GREYHOUNDS;a++)n[a].pauseAnim();playSound("photo",1,0);createjs.Tween.get(t).to({alpha:.8},
200).call(function(){var a=(new createjs.ColorMatrix).adjustSaturation(-100);q.filters=[new createjs.ColorMatrixFilter(a)];q.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k=!0;createjs.Tween.get(t).to({alpha:0},400).call(function(){s_oGame.restoreRaceAfterFlash()})})};this.restoreRaceAfterFlash=function(){setTimeout(function(){for(var a=0;a<NUM_GREYHOUNDS;a++)n[a].unpauseAnim();q.filters=[];q.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c=!0},1E3)};this._refreshRank=function(){for(var a=[],b=0;b<NUM_GREYHOUNDS;b++){var c=
n[b].getX();a[b]={index:b,x:c}}a.sort(this.compareXPos);v.refreshRank(a)};this.compareXPos=function(a,b){return a.x>b.x?-1:a.x<b.x?1:0};this.returnInBetPanel=function(){s_oGame.gotoBetPanel()};this.update=function(){if(c){var a=u.update();v.refreshRadar(a-3);for(a=0;a<NUM_GREYHOUNDS;a++)n[a].update(f);k&&q.updateCache();l+=s_iTimeElaps;l>TIME_CHECK_RANK&&(l=0,this._refreshRank())}};s_oGame=this;this._init(d)}var s_oGame=null,s_oTweenController;
function CTrackBg(b){var d,c,a,f,k,e,h;this._init=function(){f=a=c=0;k=2;e=0;h=[];for(var b=0;b<NUM_TRACK_BG;b++){var m=createBitmap(s_oSpriteLibrary.getSprite("bg_track_"+b));0<b&&(m.visible=!1);l.addChild(m);h[b]=m}d=!0};this.update=function(){if(!d)return c;e++;if(e===k){e=0;c++;if(404<=c)return;3<=c&&(a++,394==c&&(a=8),8<=a&&394>c?(h[f].x-=70,-2660==h[f].x&&(h[f].x=-770)):(h[a].visible=!0,h[f].visible=!1,f=a));403===c?(d=!1,s_oGame.checkGreyhoundArrival()):5===c&&s_oGame.startGreyhounds()}return c};
var l=b;this._init()}
function CInterface(){var b,d,c,a,f,k,e,h,l=null,g=null,m,n,p;this._init=function(){var q=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-q.width/2-10;d=q.height/2+10;m=new CGfxButton(b,d,q);m.block(!0);m.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(q=s_oSpriteLibrary.getSprite("audio_icon"),f=b-q.width/2-10,k=d,e=new CToggle(f,k,q,s_bAudioActive,s_oStage),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),c=f-q.width/2-10,a=k):(c=b-q.width-
10,a=d);q=window.document;var t=q.documentElement;l=t.requestFullscreen||t.mozRequestFullScreen||t.webkitRequestFullScreen||t.msRequestFullscreen;g=q.exitFullscreen||q.mozCancelFullScreen||q.webkitExitFullscreen||q.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(l=!1);l&&!1===inIframe()&&(q=s_oSpriteLibrary.getSprite("but_fullscreen"),h=new CToggle(c,a,q,s_bFullscreen,s_oStage),h.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));n=new CWinPanel(s_oStage);p=new CAreYouSurePanel(s_oStage)};this.refreshButtonPos=
function(g,n){e&&e.setPosition(f-g,k+n);h&&h.setPosition(c-g,a+n);m.setPosition(b-g,d+n)};this.showWinPanel=function(a,b,c){n.show(a,b,c)};this.showLosePanel=function(a){};this.unload=function(){e&&e.unload();h&&h.unload();m.unload();n.unload();p.unload();s_oInterface=null};this.blockExit=function(a){m.block(a)};this._onExit=function(){s_oGame.pause();p.show()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive;gConfig.userInfo.forSound=s_bAudioActive;gConfig.updateUserInfo()};
this.resetFullscreenBut=function(a){h&&h.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?g.call(window.document):l.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CBetPanel(){var b,d,c,a,f,k,e,h,l,g,m,n,p,q,t,u,r,v;this._init=function(){l=h=e=0;g=[];s_oBetList.reset();var w=createBitmap(s_oSpriteLibrary.getSprite("bg_bet_panel"));s_oStage.addChild(w);w=s_oSpriteLibrary.getSprite("but_home");f=CANVAS_WIDTH-w.width/2-10;k=w.height/2+10;m=new CGfxButton(f,k,w,s_oStage);m.addEventListener(ON_MOUSE_UP,this.onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var x=s_oSpriteLibrary.getSprite("audio_icon");c=f-w.width-10;a=x.height/2+10;n=new CToggle(c,
a,x,s_bAudioActive,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}w=window.document;x=w.documentElement;_fRequestFullScreen=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;_fCancelFullScreen=w.exitFullscreen||w.mozCancelFullScreen||w.webkitExitFullscreen||w.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(_fRequestFullScreen=!1);_fRequestFullScreen&&!1===inIframe()&&(x=s_oSpriteLibrary.getSprite("but_fullscreen"),b=x.width/4+10,d=x.height/
2+10,p=new CToggle(b,d,x,s_bFullscreen,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));w=s_oSpriteLibrary.getSprite("simple_bet_panel");BET_PANEL_WIDTH=w.width;BET_PANEL_HEIGHT=w.height;q=new createjs.Container;q.x=BET_PANEL_X;q.y=BET_PANEL_Y;s_oStage.addChild(q);u=new createjs.Shape;u.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(BET_PANEL_X+6,0,BET_PANEL_WIDTH-12,BET_PANEL_HEIGHT);u.y=BET_PANEL_Y;s_oStage.addChild(u);q.mask=u;t=[];t[0]=new CSimpleBetPanel(0,0,q);
r=new CChipPanel(773,230,s_oStage);v=new CMsgBox;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){createjs.Tween.removeAllTweens();p&&p.unload();n&&n.unload();m.unload();v.unload();r.unload();for(var a=0;a<t.length;a++)t[a].unload();s_oStage.removeAllChildren();s_oBetPanel=null};this.refreshButtonPos=function(e,g){n&&n.setPosition(c-e,a+g);p&&p.setPosition(b-e,d+g);m.setPosition(f-e,k+g);BET_PANEL_Y=(CANVAS_HEIGHT-BET_PANEL_HEIGHT-70)/2+70;q.y=BET_PANEL_Y;u.y=BET_PANEL_Y};this.setChipSelected=
function(a){l=a};this.getChipSelected=function(){return l};this.setSimpleBet=function(a,b,c,e){var f=GAME_ODDS_RATE[MY_ODDS.COIN_TYPE];if(h+c>MAX_BET)return v.show(TEXT_ERR_MAX_BET+"\n"+TEXT_MAX_BET+": "+MAX_BET+" CHIP",!0,!0);if((h+c)*f>s_iCurMoney)return v.show(TEXT_NO_MONEY,!0,!0);s_oBetList.addSimpleBet(a,b,c);h+=c;r.refreshBet(h*f);g.push(e);return!0};this.setForecastBet=function(a,b,c,e){var f=GAME_ODDS_RATE[MY_ODDS.COIN_TYPE];if(h+c>MAX_BET)return v.show(TEXT_ERR_MAX_BET+"\n"+TEXT_MAX_BET+
": "+MAX_BET+" CHIP",!0,!0);if((h+c)*f>s_iCurMoney)return v.show(TEXT_NO_MONEY,!0,!0);s_oBetList.addForecastBet(a,b,c);h+=c;r.refreshBet(h*f);g.push(e);return!0};this.refreshPagePos=function(a,b){q.x=BET_PANEL_X;t[e].setX(0);t[a].setX(b)};this.clearBet=function(){for(var a=0;a<g.length;a++)g[a].clearBet();h=0;t[0].clearBet();s_oBetList.reset();r.refreshBet(0)};this._onArrowLeft=function(){var a=e;e++;e===t.length&&(e=0,a=t.length-1);(void 0).text=eval("TEXT_HELP_PAGE_"+e);t[e].setX(BET_PANEL_WIDTH);
createjs.Tween.get(q).to({x:-BET_PANEL_WIDTH+BET_PANEL_X},500,createjs.Ease.cubicOut).call(function(){s_oBetPanel.refreshPagePos(a,BET_PANEL_WIDTH)})};this._onArrowRight=function(){var a=e;e--;0>e&&(e=t.length-1);(void 0).text=eval("TEXT_HELP_PAGE_"+e);t[e].setX(-BET_PANEL_WIDTH);createjs.Tween.get(q).to({x:BET_PANEL_X+BET_PANEL_WIDTH},500,createjs.Ease.cubicOut).call(function(){s_oBetPanel.refreshPagePos(a,-BET_PANEL_WIDTH)})};this.updateCredit=function(a){s_iCurMoney=START_CREDIT;r.refreshMoney()};
this.onStartRace=function(){h<MIN_BET?v.show(TEXT_ERR_MIN_BET,!0,!0):userBetSend(betPlace,h,this.serverReturns)};this.serverReturns=function(a){if(!(1>a)){a--;for(var b=shuffle([0,1,2,3,4,5]),c=[a],e=0;e<b.length;e++)b[e]!=a&&c.push(b[e]);this.unload();s_oMain.gotoGame(h,c)}};this.serverResultBetRequest=function(a){this.unload();s_oMain.gotoGame(h,a)};this.onExit=function(){$("#contractModal").modal("show")};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive;
gConfig.userInfo.forSound=s_bAudioActive;gConfig.updateUserInfo()};this.resetFullscreenBut=function(a){p&&p.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?_fCancelFullScreen.call(window.document):_fRequestFullScreen.call(window.document.documentElement);sizeHandler()};s_oBetPanel=this;this._init()}var s_oBetPanel=null;
function CChipPanel(b,d,c){var a,f,k,e,h,l,g,m;this._init=function(a,b){m=new createjs.Container;m.x=a;m.y=b;n.addChild(m);k=new CTextButton(100,30,s_oSpriteLibrary.getSprite("but_clear_bet"),TEXT_CLEAR_BET,PRIMARY_FONT,"#fff",22,m);k.addEventListener(ON_MOUSE_UP,this._onClearBet,this);var c=s_oSpriteLibrary.getSprite("money_panel"),f=createBitmap(s_oSpriteLibrary.getSprite("money_panel"));f.regX=c.width/2;f.x=100;f.y=62;m.addChild(f);l=new createjs.Text(TEXT_MAX_BET+": "+game_MaxBet_newTRX,"19px "+
SECONDARY_FONT,"#ffde00");l.textAlign="center";l.textBaseline="alphabetic";l.x=100;l.y=f.y+29;m.addChild(l);f=createBitmap(s_oSpriteLibrary.getSprite("money_panel"));f.regX=c.width/2;f.x=100;f.y=132;m.addChild(f);c=new createjs.Text(TEXT_BET,"18px "+TERTIARY_FONT,"#fff");c.textAlign="left";c.textBaseline="alphabetic";c.x=3;c.y=f.y;m.addChild(c);g=new createjs.Text("0 "+MY_BALANCES[MY_ODDS.COIN_TYPE].name,"26px "+SECONDARY_FONT,"#ffde00");g.textAlign="center";g.textBaseline="alphabetic";g.x=100;g.y=
f.y+32;m.addChild(g);c=s_oSpriteLibrary.getSprite("money_bg");f=createBitmap(c);f.x=76;f.y=122;s_oStage.addChild(f);h=new createjs.Text("","22px "+WEB_FONT,"#ffde00");h.textAlign="center";h.lineHeight=26;h.textBaseline="alphabetic";h.x=153;h.y=150;s_oStage.addChild(h);e=new CButStartRace(100,344,s_oSpriteLibrary.getSprite("but_start_race"),TEXT_START_RACE,"#fff",24,m);e.addEventListener(ON_MOUSE_UP,this._onStartRace,this);this._initChips();this._setOddCoinType(MY_ODDS.COIN_TYPE)};this.unload=function(){for(var b=
0;b<a;b++)a[b].unload();k.unload();e.unload()};this._initChips=function(){var b=createBitmap(s_oSpriteLibrary.getSprite("fiche_panel"));b.x=0;b.y=184;m.addChild(b);var c=[{x:46,y:35},{x:101,y:35},{x:153,y:35},{x:46,y:88},{x:101,y:88},{x:153,y:88}];a=[];for(var e=0;e<NUM_CHIPS;e++){var d=s_oSpriteLibrary.getSprite("fiche_"+e);a[e]=new CGfxButton(c[e].x,c[e].y+b.y,d,m);a[e].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,e)}b=s_oSpriteLibrary.getSprite("fiche_highlight");f=createBitmap(b);
f.regX=b.width/2;f.regY=b.height/2;m.addChild(f)};this._setChips=function(){this._onFicheClicked(MY_ODDS.ODDS[MY_ODDS.COIN_TYPE])};this.refreshMoney=function(){var a=START_CREDIT;a=numberFormat(a,{decimals:2,clear_decimals:!0,limit_length_decimals:10});h.text=MY_BALANCES[MY_ODDS.COIN_TYPE].name+"\n"+a};this.refreshBet=function(a){a&&(a=numberFormat(a,{decimals:8,clear_decimals:!0,limit_length_decimals:10}));g.text=a+" "+MY_BALANCES[MY_ODDS.COIN_TYPE].name};this._onStartRace=function(){s_oBetPanel.onStartRace()};
this._onClearBet=function(){s_oBetPanel.clearBet()};this._onFicheClicked=function(b){f.x=a[b].getX()-1;f.y=a[b].getY()-1;s_oBetPanel.setChipSelected(b);MY_ODDS.ODDS[MY_ODDS.COIN_TYPE]!=b&&(MY_ODDS.ODDS[MY_ODDS.COIN_TYPE]=b,gConfig.userInfo.MY_ODDS=MY_ODDS,gConfig.updateUserInfo())};this._onSelectCoin=function(){var a=(void 0).getCurrentFrame();a++;2<a&&(a=0);MY_ODDS.COIN_TYPE=a;gConfig.userInfo.MY_ODDS=MY_ODDS;gConfig.updateUserInfo();this._setOddCoinType(MY_ODDS.COIN_TYPE);this._onClearBet()};this._setOddCoinType=
function(a){s_iCurMoney=Number(MY_BALANCES[MY_ODDS.COIN_TYPE].available);this.refreshMoney();this._setChips()};this._onShowHelp=function(a){$("#game_guide").show()};var n=c;this._init(b,d)}
function CSimpleBetPanel(b,d,c){var a,f,k,e,h,l;this._init=function(a,b){l=new createjs.Container;l.x=a;l.y=b;g.addChild(l);var c=createBitmap(s_oSpriteLibrary.getSprite("simple_bet_panel"));l.addChild(c);c=new createjs.Text(TEXT_TRAP,"20px "+PRIMARY_FONT,"#fff");c.textAlign="center";c.textBaseline="alphabetic";c.x=56;c.y=24;l.addChild(c);c=new createjs.Text(TEXT_GREYHOUND_NAME,"20px "+PRIMARY_FONT,"#fff");c.textAlign="center";c.textBaseline="alphabetic";c.x=180;c.y=24;l.addChild(c);c=new createjs.Text("PLACE A BET",
"20px "+PRIMARY_FONT,"#fff");c.textAlign="center";c.textBaseline="alphabetic";c.x=500;c.y=24;l.addChild(c);c=s_oSpriteLibrary.getSprite("bibs");for(var e=new createjs.SpriteSheet({images:[c],frames:{width:c.width/3,height:c.height/2},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}}),f=38,d=0;d<NUM_GREYHOUNDS;d++){var m=createSprite(e,"bib_"+d);m.x=28;m.y=f;l.addChild(m);f+=c.height/2+11}this._initGreyhoundInfos();this._initBetPlaces()};this._initGreyhoundInfos=function(){var b=
s_oGameSettings.getAllGreyhoundNames();a=[];for(var c=104,e=0;e<NUM_GREYHOUNDS;e++){var f={framerate:40,images:[s_oSpriteLibrary.getSprite("greyhound_"+(e+1))],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[0,0],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};f=new createjs.SpriteSheet(f);f=createSprite(f,"idle");f.x=150;f.y=c;f.scaleX=f.scaleY=.5;l.addChild(f);a.push(f);f=new createjs.Text(b[e].toUpperCase(),
"16px "+TERTIARY_FONT,"#fff");f.textAlign="right";f.textBaseline="alphabetic";f.x=286;f.y=c-10;l.addChild(f);c+=67}};this._initBetPlaces=function(){e=[];h=[];k=[];f=[];for(var a=66,b=s_oSpriteLibrary.getSprite("bet_place"),c=0;c<NUM_GREYHOUNDS;c++){var d=new createjs.Text("x"+s_oGameSettings.getOddWin(c),"20px "+TERTIARY_FONT,"#fff");d.textAlign="center";d.textBaseline="middle";d.x=465;d.y=a+18;l.addChild(d);f[c]=d;d=new CButBet(d.x+60,a,b,.7,l,1);d.addEventListenerWithParams(ON_MOUSE_UP,this._onWinClicked,
this,c);k.push(d);a+=67}};this.unload=function(){for(var a=0;a<e.length;a++)k[a].unload(),h[a].unload(),e[a].unload()};this.setX=function(a){l.x=a};this.clearBet=function(){for(var b=0;b<a.length;b++)a[b].gotoAndStop("idle");for(b=0;b<k.length;b++)f[b].visible=!0,k[b].setVisibleB(!0)};this._onWinClicked=function(b){var c=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(b,1,c,k[b])&&(k[b].increaseBet(c),a[b].gotoAndPlay("anim"));window.betPlace=b+1;for(c=0;c<k.length;c++)c!=b&&(f[c].visible=
!1,k[c].setVisibleB(!1))};this._onPlaceClicked=function(b){var c=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(b,2,c,e[b])&&(e[b].increaseBet(c),a[b].gotoAndPlay("anim"))};this._onShowClicked=function(b){var c=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(b,3,c,h[b])&&(h[b].increaseBet(c),a[b].gotoAndPlay("anim"))};this.getContainer=function(){return l};var g=c;this._init(b,d)}
function CForecastPanel(b,d,c){var a,f;this._init=function(){f=new createjs.Container;f.x=b;f.y=d;k.addChild(f);var a=createBitmap(s_oSpriteLibrary.getSprite("forecast_panel"));f.addChild(a);this._initForecastBets()};this.unload=function(){for(var b in a)-1<b.indexOf("forecast_")&&a[b].unload()};this._initForecastBets=function(){a=[];for(var b=[{x:26,y:10},{x:256,y:10},{x:486,y:10},{x:26,y:225},{x:256,y:225},{x:486,y:225}],c=0;c<NUM_GREYHOUNDS;c++)this._placeForecastBetForGreyhound(c,b[c].x,b[c].y)};
this._placeForecastBetForGreyhound=function(b,c,d){var e=s_oSpriteLibrary.getSprite("odd_bg"),k=s_oSpriteLibrary.getSprite("bet_place"),h=s_oSpriteLibrary.getSprite("bibs"),l=h.width/3,q=h.height/2;h=new createjs.SpriteSheet({images:[h],frames:{width:l,height:q},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});for(var t=0;t<NUM_GREYHOUNDS;t++)if(t!==b){var u=createSprite(h,"bib_"+b);u.x=c;u.y=d;u.scaleX=u.scaleY=.65;f.addChild(u);var r=new createjs.Text("&","16px "+PRIMARY_FONT,
"#fff");r.textAlign="center";r.textBaseline="middle";r.x=c+.65*l+10;r.y=d+.65*q/2;f.addChild(r);var v=createSprite(h,"bib_"+t);v.x=r.x+10;v.y=u.y;v.scaleX=v.scaleY=.65;f.addChild(v);r=createBitmap(e);r.x=v.x+.65*l+10;r.y=u.y+2;f.addChild(r);u=new createjs.Text("x"+s_oGameSettings.getForecastOdd(b,t),"18px "+TERTIARY_FONT,"#fff");u.textAlign="center";u.textBaseline="alphabetic";u.x=r.x+e.width/2;u.y=r.y+e.height-2;f.addChild(u);u=new CButBet(r.x+e.width+.72*k.width/2+5,r.y+.72*k.height/2,k,.45,f,2);
u.setScale(.72);u.addEventListenerWithParams(ON_MOUSE_UP,this._onForecastClicked,this,{first:b,second:t});a["forecast_"+b+"_"+t]=u;d+=.65*q+5}};this.setX=function(a){f.x=a};this._onForecastClicked=function(b){var c=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setForecastBet(b.first,b.second,c,a["forecast_"+b.first+"_"+b.second])&&a["forecast_"+b.first+"_"+b.second].increaseBet(c)};var k=c;this._init(b,d)}
function CBetList(){var b,d,c;this._init=function(){this.reset()};this.reset=function(){b=[];for(var a=0;a<NUM_GREYHOUNDS;a++)b[a]=[],b[a].place_1=0,b[a].place_2=0,b[a].place_3=0;d=[];for(a=0;a<NUM_GREYHOUNDS;a++){d[a]=[];for(var f=0;f<NUM_GREYHOUNDS;f++)d[a][f]=0}c=[]};this.addSimpleBet=function(a,f,d){b[a]["place_"+f]+=d;var e=0;switch(f){case 1:e=d*s_oGameSettings.getOddWin(a);break;case 2:e=d*s_oGameSettings.getOddPlace(a);break;case 3:e=d*s_oGameSettings.getOddShow(a)}c.push({type_bet:"simple",
greyhounds:[{index:a,place:f}],bet:d,win:e})};this.addForecastBet=function(a,b,k){d[a][b]+=k;c.push({type_bet:"forecast",greyhounds:[{index:a,place:1},{index:b,place:2}],bet:k,win:k*s_oGameSettings.getForecastOdd(a,b)})};this.getMinWin=function(){if(0<c.length){for(var a=c[0].win,b=1;b<c.length;b++)a>c[b].win&&(a=c[b].win);return a}return 0};this.getTotWinWithCurRank=function(a){var c=0,k=[];if(0<b[a[0]].place_1){var e=b[a[0]].place_1*s_oGameSettings.getOddWin(a[0]);e=parseFloat(e.toFixed(2));c+=
e;k.push({win:e,greyhounds:a[0],bet:b[a[0]].place_1,type:"win"})}0<b[a[0]].place_2&&(e=b[a[0]].place_2*s_oGameSettings.getOddPlace(a[0]),e=parseFloat(e.toFixed(2)),c+=e,k.push({win:e,greyhounds:a[0],bet:b[a[0]].place_2,type:"place"}));0<b[a[1]].place_2&&(e=b[a[1]].place_2*s_oGameSettings.getOddPlace(a[1]),e=parseFloat(e.toFixed(2)),c+=e,k.push({win:e,greyhounds:a[1],bet:b[a[1]].place_2,type:"place"}));0<b[a[0]].place_3&&(e=b[a[0]].place_3*parseFloat(s_oGameSettings.getOddShow(a[0])),e=parseFloat(e.toFixed(2)),
c+=e,k.push({win:e,greyhounds:a[0],bet:b[a[0]].place_3,type:"show"}));0<b[a[1]].place_3&&(e=b[a[1]].place_3*s_oGameSettings.getOddShow(a[1]),e=parseFloat(e.toFixed(2)),c+=e,k.push({win:e,greyhounds:a[1],bet:b[a[1]].place_3,type:"show"}));0<b[a[2]].place_3&&(e=b[a[2]].place_3*s_oGameSettings.getOddShow(a[2]),e=parseFloat(e.toFixed(2)),c+=e,k.push({win:e,greyhounds:a[2],bet:b[a[2]].place_3,type:"show"}));0<d[a[0]][a[1]]&&(e=d[a[0]][a[1]]*s_oGameSettings.getForecastOdd(a[0],a[1]),e=parseFloat(e.toFixed(2)),
c+=e,k.push({win:e,greyhounds:[a[0],a[1]],bet:d[a[0]][a[1]],type:"forecast"}));return{tot_win:c,win_list:k}};s_oBetList=this;this._init()}var s_oBetList=null;
function CFichesController(b,d,c){var a,f,k,e,h,l,g,m,n,p,q;this._init=function(b){e=b;n=new createjs.Container;t.addChild(n);l=new CVector2;l.set(n.x,n.y);p=new createjs.Container;t.addChild(p);q=new createjs.Text("","18px "+PRIMARY_FONT,"#ffff00");q.textAlign="center";p.addChild(q);k=h=f=0;a=!1};this.addEventListener=function(a,b,c){};this.reset=function(){a=!1;k=0;n.removeAllChildren();n.x=l.getX();n.y=l.getY();q.text=""};this.setPrevValue=function(a){h=a};this.refreshFiches=function(a,c,f){a=
a.sortOn("value","index");for(var d=f,g=k=0,h=0;h<a.length;h++)if(k+=a[h].value,!(10<=h)){var l=s_oSpriteLibrary.getSprite("fiche_"+a[h].index),m=createBitmap(l);m.regX=l.width/2;m.regY=l.height/2;m.scaleX=b;m.scaleY=b;n.addChild(m);m.x=c;m.y=d;d-=6*b;g++}playSound("chip",1,0);1==u?(q.x=c-52,q.y=f-25*e):(q.x=c-30,q.y=f-16);q.text=k};this.createFichesPile=function(a,b,c){this.reset();var f=CHIP_VALUES,d=[];do{for(var g=f[f.length-1],h=f.length-1;g>a;)h--,g=f[h];h=Math.floor(a/g);for(var k=0;k<h;k++)d.push({value:g,
index:s_oGameSettings.getIndexForFiches(g)});g=Math.floor(a/g)===a/g?0:a%g;a=g.toFixed(2)}while(0<g);this.refreshFiches(d,b,c*e)};this.initMovement=function(b,c){h=k;g=new CVector2(n.x,n.y);m=new CVector2(b,c);q.text="";a=!0};this.getValue=function(){return k};this.getPrevBet=function(){return h};this.update=function(b){if(a)if(f+=b,f>TIME_FICHES_MOV)f=0,a=!1;else{b=easeInOutCubic(f,0,1,TIME_FICHES_MOV);var c=new CVector2;c=tweenVectors(g,m,b,c);n.x=c.getX();n.y=c.getY()}};var t=d;var u=c;this._init(b)}
function CButBet(b,d,c,a,f,k){var e,h,l,g,m,n,p,q,t,u=!1,r,v;this._init=function(a,b,c,f,d){e=0;h=[];l=[];m=[];v=new createjs.Container;v.x=a;v.y=b;w.addChild(v);g=createBitmap(c);p=n=1;g.regX=c.width/2;g.regY=c.height/2;s_bMobile||(g.cursor="pointer");v.addChild(g);this._initListener();r=new CFichesController(f,v,d)};this.unload=function(){g.off("mousedown",q);g.off("pressup",t);w.removeChild(v)};this.setVisibleB=function(a){g.alpha=a?1:.5;this.block(!a)};this.setVisible=function(a){g.visible=a};
this.setCursorType=function(a){g.cursor=a};this._initListener=function(){q=g.on("mousedown",this.buttonDown);t=g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;l[a]=c};this.addEventListenerWithParams=function(a,b,c,f){h[a]=b;l[a]=c;m[a]=f};this.buttonRelease=function(){u||(g.scaleX=0<n?n:-n,g.scaleY=p,playSound("chip",1,0),h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP],m[ON_MOUSE_UP]))};this.buttonDown=function(){u||(g.scaleX=0<n?.9*n:.9*-n,g.scaleY=.9*p,h[ON_MOUSE_DOWN]&&
h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],m[ON_MOUSE_DOWN]))};this.rotation=function(a){g.rotation=a};this.getButton=function(){return g};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.block=function(a){u=a;g.scaleX=n;g.scaleY=p};this.setScaleX=function(a){n=g.scaleX=a};this.setScale=function(a){p=n=a;g.scaleX=g.scaleY=a};this.increaseBet=function(a){e+=a;r.createFichesPile(e.toFixed(2),0,-4)};this.clearBet=
function(){e=0;r.reset()};this.getX=function(){return g.x};this.getY=function(){return g.y};this.pulseAnimation=function(){createjs.Tween.get(g).to({scaleX:.9*n,scaleY:.9*p},850,createjs.Ease.quadOut).to({scaleX:n,scaleY:p},650,createjs.Ease.quadIn).call(function(){x.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(g).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){x.trebleAnimation()})};
this.removeAllTweens=function(){createjs.Tween.removeTweens(g)};var w=void 0!==f?f:s_oStage;this._init(b,d,c,a,k);var x=this;return this}
function CVector2(b,d){var c,a;this._init=function(b,d){c=b;a=d};this.add=function(b,d){c+=b;a+=d};this.addV=function(b){c+=b.getX();a+=b.getY()};this.scalarDivision=function(b){c/=b;a/=b};this.subV=function(b){c-=b.getX();a-=b.getY()};this.scalarProduct=function(b){c*=b;a*=b};this.invert=function(){c*=-1;a*=-1};this.dotProduct=function(b){return c*b.getX()+a*b.getY()};this.set=function(b,d){c=b;a=d};this.setV=function(b){c=b.getX();a=b.getY()};this.length=function(){return Math.sqrt(c*c+a*a)};this.length2=
function(){return c*c+a*a};this.normalize=function(){var b=this.length();0<b&&(c/=b,a/=b)};this.getNormalize=function(b){this.length();b.set(c,a);b.normalize()};this.rot90CCW=function(){var b=c;c=-a;a=b};this.rot90CW=function(){var b=c;c=a;a=-b};this.getRotCCW=function(b){b.set(c,a);b.rot90CCW()};this.getRotCW=function(b){b.set(c,a);b.rot90CW()};this.ceil=function(){c=Math.ceil(c);a=Math.ceil(a)};this.round=function(){c=Math.round(c);a=Math.round(a)};this.toString=function(){return"Vector2: "+c+", "+
a};this.print=function(){trace("Vector2: "+c+", "+a)};this.getX=function(){return c};this.getY=function(){return a};this._init(b,d)}
function CMsgBox(){var b,d,c,a,f,k,e,h,l;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d=new createjs.Text("","30px "+PRIMARY_FONT,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-40;d.textAlign="center";d.lineWidth=400;d.lineHeight=48;d.textBaseline="middle";a=new createjs.Container;a.alpha=0;a.visible=!1;a.addChild(b,d);s_oStage.addChild(a)};this.unload=function(){this._onExit(!0)};this._initListener=function(){f=a.on("mousedown",this._onExit)};this.show=function(b,
f,n,p){if(!a.visible){a.visible=!0;c=b;d.text=c;a.alpha=0;k=!1;this._initListener();var g=this;e=createjs.Tween.get(a).to({alpha:1},200).call(function(){f&&(k=!0)});p&&(h=a.addEventListener("tick",this._update));n&&(l=setTimeout(function(){g._onExit()},3E3))}};this.hide=function(){this._onExit(!0)};this._update=function(a){a=createjs.Ticker.getTicks();0==a%10&&(d.text=c+"...".substring(0,a/10%3+1))};this._onExit=function(b){if(k||!0===b)a.off("mousedown",f),f=null,e&&createjs.Tween.removeTweens(e),
e=null,h&&a.off("tick",h),h=null,l&&clearTimeout(l),l=null,a.visible=!1};this._init();return this}
function CGreyhound(b,d,c,a,f,k){var e,h,l,g,m,n,p,q,t,u,r;this._init=function(a,b,c,e,d){h=!1;l=b;p=0;q=ARRIVAL_X-GREYHOUND_WIDTH/2*e+30;t=c;u=d;b={framerate:40,images:[s_oSpriteLibrary.getSprite("greyhound_"+b)],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[0,0],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};b=new createjs.SpriteSheet(b);r=createSprite(b,"start");r.x=a.x;r.y=a.y;r.scaleX=
r.scaleY=e;r.alpha=0;v.addChild(r)};this.startRace=function(){var a="anim_"+(Math.floor(3*Math.random())+1);createjs.Tween.get(r).to({alpha:1},150).call(function(){r.gotoAndPlay(a)});n=r.x;g=0;m=u[p].frame;e=!0};this.pauseAnim=function(){r.paused=!0};this.unpauseAnim=function(){r.paused=!1};this.getX=function(){return r.x};this.update=function(a){if(e){g++;if(g>=m)p++,p<u.length?(g=0,m=u[p].frame,n=r.x):e=!1;else{var b=s_oTweenController.easeLinear(g,0,1,m);b=s_oTweenController.tweenValue(n,u[p].x,
b);r.x=b}a&&!h&&r.x>=q&&(h=!0,s_oGame.greyhoundPhotofinish(l-1,t))}};var v=k;this._init(b,d,c,a,f)}
function CTweenController(){this.tweenValue=function(b,d,c){return b+c*(d-b)};this.easeLinear=function(b,d,c,a){return c*b/a+d};this.easeInCubic=function(b,d,c,a){a=(b/=a)*b*b;return d+c*a};this.easeBackInQuart=function(b,d,c,a){a=(b/=a)*b;return d+c*(2*a*a+2*a*b+-3*a)};this.easeInBack=function(b,d,c,a){return c*(b/=a)*b*(2.70158*b-1.70158)+d};this.easeOutCubic=function(b,d,c,a){return c*((b=b/a-1)*b*b+1)+d};this.getTrajectoryPoint=function(b,d){var c=new createjs.Point,a=(1-b)*(1-b),f=b*b;c.x=a*
d.start.x+2*(1-b)*b*d.traj.x+f*d.end.x;c.y=a*d.start.y+2*(1-b)*b*d.traj.y+f*d.end.y;return c}}
function CRankingGui(b,d){var c,a,f,k,e,h,l;this._init=function(b){var d=s_oSpriteLibrary.getSprite("rank_panel");c=CANVAS_HEIGHT-d.height+6;l=new createjs.Container;l.x=0;l.y=c;g.addChild(l);d=createBitmap(d);l.addChild(d);k=[];k[0]=new createjs.Point(780,48);k[1]=new createjs.Point(642,48);k[2]=new createjs.Point(504,48);k[3]=new createjs.Point(366,48);k[4]=new createjs.Point(228,48);k[5]=new createjs.Point(90,48);this._initBibs(b);a=2;e=createBitmap(s_oSpriteLibrary.getSprite("fill_bar"));e.x=
107;e.y=116;l.addChild(e);h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y-2,.01,10);l.addChild(h);e.mask=h;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(a,b){l.y=c-b};this._initBibs=function(a){f=[];for(var b=0;b<NUM_GREYHOUNDS;b++){var c=new createjs.Container;c.x=k[b].x;c.y=k[b].y;l.addChild(c);var e=createBitmap(s_oSpriteLibrary.getSprite("bib_gui_"+b));c.addChild(e);e=new createjs.Text(a[b].toUpperCase(),"14px "+PRIMARY_FONT,
"#fff");e.textAlign="right";e.textBaseline="alphabetic";e.x=50;e.y=10;c.addChild(e);f.push(c)}};this.refreshRank=function(a){for(var b=0;b<a.length;b++)createjs.Tween.get(f[a[b].index]).to({x:k[b].x},1E3,createjs.Ease.cubicOut)};this.refreshRadar=function(b){h.graphics.clear();h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y-2,a*b,10)};var g=d;this._init(b)}
function CArrivalPanel(b,d,c){var a,f,k,e,h,l,g;this._init=function(b,c){e=0;f=b;k=c;g=new createjs.Container;g.x=f;g.y=k;m.addChild(g);var d=s_oSpriteLibrary.getSprite("panel_arrival");d=createBitmap(d);g.addChild(d);d=s_oSpriteLibrary.getSprite("bibs");var n=d.width/3,u=d.height/2,r=new createjs.SpriteSheet({images:[d],frames:{width:n,height:u},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});h=[];l=[];for(var p=6,w=0;w<NUM_GREYHOUNDS;w++){var x=createSprite(r,"bib_0");
x.x=10;x.y=p;x.visible=!1;x.scaleX=x.scaleY=.5;g.addChild(x);l.push(x);var y=new createjs.Text("","15px "+TERTIARY_FONT,"#fff");y.textAlign="left";y.textBaseline="alphabetic";y.x=x.x+.5*n+5;y.y=x.y+26;g.addChild(y);h.push(y);p+=.5*u+4}a=CANVAS_WIDTH-d.width};this.show=function(){createjs.Tween.get(g).to({x:a},500,createjs.Ease.cubicOut)};this.hide=function(){createjs.Tween.get(g).to({x:f},500,createjs.Ease.cubicOut)};this.refreshRank=function(a,b){h[e].text=b;l[e].gotoAndStop("bib_"+a);l[e].visible=
!0;0===e&&this.show();e++};var m=c;this._init(b,d)}
function CWinPanel(b){var d,c,a,f,k,e,h,l;this._init=function(){h=new createjs.Container;h.visible=!1;g.addChild(h);l=h.on("click",function(){});var b=createBitmap(s_oSpriteLibrary.getSprite("win_panel"));h.addChild(b);b=s_oSpriteLibrary.getSprite("bibs");d=b.width/3;c=b.height/2;a=new createjs.SpriteSheet({images:[b],frames:{width:d,height:c},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});e=new createjs.Text(TEXT_NO_WIN,"45px "+PRIMARY_FONT,"#fff");e.textAlign="center";
e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2-120;e.y=285;e.visible=!1;h.addChild(e);k=new createjs.Text(TEXT_WIN,"30px "+SECONDARY_FONT,"#ffde00");k.textAlign="center";k.textBaseline="alphabetic";k.x=CANVAS_WIDTH/2+70;k.y=476;k.lineHeight=42;h.addChild(k);f=new CGfxButton(700,489,s_oSpriteLibrary.getSprite("but_skip"),h);f.addEventListener(ON_MOUSE_UP,this.onSkip,this)};this.unload=function(){h.off("click",l);f.unload()};this.show=function(b,c,f){if(b)for(var g=CANVAS_HEIGHT/2-150,l=0;l<c.length;l++){if("forecast"===
c[l].type){var m=c[l].greyhounds;var n=createSprite(a,"bib_"+m[0]);n.x=280;n.y=g;n.scaleX=n.scaleY=.5;h.addChild(n);var p=new createjs.Text("&","20px "+PRIMARY_FONT,"#fff");p.textAlign="center";p.textBaseline="middle";p.x=n.x+.5*d+10;p.y=g+15;h.addChild(p);m=createSprite(a,"bib_"+m[1]);m.x=p.x+10;m.y=g;m.scaleX=m.scaleY=.5;h.addChild(m);m=m.x+35}else n=createSprite(a,"bib_"+c[l].greyhounds),n.x=280,n.y=g,n.scaleX=n.scaleY=.5,h.addChild(n),m=n.x+35;p=new createjs.Text(c[l].type.toUpperCase(),"20px "+
PRIMARY_FONT,"#ffb400");p.textAlign="left";p.textBaseline="alphabetic";p.x=m;p.y=g+22;h.addChild(p);m=GAME_ODDS_RATE[MY_ODDS.COIN_TYPE];m=Number(numberFormat(c[l].win*m,{decimals:8,clear_decimals:!0,sep:""}));m=new createjs.Text(TEXT_WIN+": "+m,"20px "+PRIMARY_FONT,"#fff");m.textAlign="left";m.textBaseline="alphabetic";"forecast"===c[l].type?(m.x=p.x+1,g+=22):m.x=p.x+p.getBounds().width+10;m.y=g+22;h.addChild(m);g+=35}else e.visible=!0;m=GAME_ODDS_RATE[MY_ODDS.COIN_TYPE];m=Number(numberFormat(b*m,
{decimals:8,clear_decimals:!0,sep:""}));k.text=TEXT_WIN+"\n"+m;g=310;for(b=0;3>b;b++)c={images:[s_oSpriteLibrary.getSprite("greyhound_"+(f[b]+1))],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[18,18],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}},c=new createjs.SpriteSheet(c),c=createSprite(c,"idle"),c.scaleX=c.scaleY=.5,c.x=CANVAS_WIDTH/2+150,c.y=g,c.gotoAndPlay("anim"),h.addChild(c),
g+=68;h.visible=!0;h.alpha=0;createjs.Tween.get(h).wait(1E3).to({alpha:1},500,createjs.Ease.cubicOut)};this.onSkip=function(){s_oGame.returnInBetPanel()};var g=b;this._init()}
function CButStartRace(b,d,c,a,f,k,e){var h,l,g,m,n,p,q;this._init=function(a,b,c,e,d,f){h=[];l=[];var k=createBitmap(c),p=Math.ceil(f/20);n=new createjs.Text(e,"bold "+f+"px "+PRIMARY_FONT,"#000000");n.textAlign="center";n.textBaseline="alphabetic";n.x=c.width/2+p;n.y=28;m=new createjs.Text(e,"bold "+f+"px "+PRIMARY_FONT,d);m.textAlign="center";m.textBaseline="alphabetic";m.x=c.width/2;m.y=26;g=new createjs.Container;g.x=a;g.y=b;g.regX=c.width/2;g.regY=c.height/2;g.addChild(k,n,m);t.addChild(g);
s_bMobile||(g.cursor="pointer");this._initListener()};this.unload=function(){g.off("mousedown",p);g.off("pressup",q);t.removeChild(g)};this.setVisible=function(a){g.visible=a};this._initListener=function(){p=g.on("mousedown",this.buttonDown);q=g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;l[a]=c};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;playSound("click",1,0);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=function(){g.scaleX=.9;g.scaleY=
.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;n.y=a+2};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};var t=e;this._init(b,d,c,a,f,k);return this}
function CAreYouSurePanel(b){var d,c,a,f;this._init=function(){a=new createjs.Container;a.visible=!1;f=a.on("click",function(){});k.addChild(a);var b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));a.addChild(b);b=new createjs.Text(TEXT_ARE_YOU_SURE,"30px "+PRIMARY_FONT,"#fff");b.textAlign="center";b.textBaseline="alphabetic";b.x=CANVAS_WIDTH/2;b.y=280;b.lineWidth=400;b.lineHeight=48;a.addChild(b);d=new CGfxButton(CANVAS_WIDTH/2+170,460,s_oSpriteLibrary.getSprite("but_yes"),a);d.addEventListener(ON_MOUSE_UP,
this._onReleaseYes,this);c=new CGfxButton(CANVAS_WIDTH/2-170,460,s_oSpriteLibrary.getSprite("but_no"),a);c.addEventListener(ON_MOUSE_UP,this._onReleaseNo,this)};this.unload=function(){a.off("click",f);d.unload();c.unload()};this.show=function(){a.visible=!0;a.alpha=0;createjs.Tween.get(a).to({alpha:1},500,createjs.Ease.cubicOut)};this._onReleaseYes=function(){s_oGame.onExit()};this._onReleaseNo=function(){a.visible=!1;s_oGame.unpause()};var k=b;this._init(b)};